version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./fastcampus:/srv/docker-djnago
     - ./log:/var/log/nginx
    depends_on:
     - django
    
  django:
    container_name: django
    build: .
    image: jango
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
     - ./fastcampus:/srv/docker-django
     - ./log:/var/log/uwsgi